# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Thu Aug 11 03:36:35 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(842, 620)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidgetChatConsole = QtGui.QTabWidget(self.centralwidget)
        self.tabWidgetChatConsole.setEnabled(True)
        self.tabWidgetChatConsole.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidgetChatConsole.setAutoFillBackground(False)
        self.tabWidgetChatConsole.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidgetChatConsole.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidgetChatConsole.setTabsClosable(False)
        self.tabWidgetChatConsole.setMovable(True)
        self.tabWidgetChatConsole.setObjectName(_fromUtf8("tabWidgetChatConsole"))
        self.tabChat = QtGui.QWidget()
        self.tabChat.setObjectName(_fromUtf8("tabChat"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabChat)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter = QtGui.QSplitter(self.tabChat)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeWidgetChat = QtGui.QTreeWidget(self.layoutWidget)
        self.treeWidgetChat.setFocusPolicy(QtCore.Qt.NoFocus)
        self.treeWidgetChat.setProperty(_fromUtf8("showDropIndicator"), False)
        self.treeWidgetChat.setAlternatingRowColors(True)
        self.treeWidgetChat.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.treeWidgetChat.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidgetChat.setIndentation(10)
        self.treeWidgetChat.setRootIsDecorated(False)
        self.treeWidgetChat.setItemsExpandable(False)
        self.treeWidgetChat.setAnimated(True)
        self.treeWidgetChat.setWordWrap(True)
        self.treeWidgetChat.setObjectName(_fromUtf8("treeWidgetChat"))
        self.treeWidgetChat.header().setVisible(False)
        self.verticalLayout.addWidget(self.treeWidgetChat)
        self.lineEditMessage = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditMessage.setObjectName(_fromUtf8("lineEditMessage"))
        self.verticalLayout.addWidget(self.lineEditMessage)
        self.treeWidgetPlayersList = QtGui.QTreeWidget(self.splitter)
        self.treeWidgetPlayersList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidgetPlayersList.setBaseSize(QtCore.QSize(0, 0))
        self.treeWidgetPlayersList.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.treeWidgetPlayersList.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidgetPlayersList.setIndentation(15)
        self.treeWidgetPlayersList.setObjectName(_fromUtf8("treeWidgetPlayersList"))
        self.treeWidgetPlayersList.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidgetPlayersList.header().setVisible(False)
        self.horizontalLayout_2.addWidget(self.splitter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../Pictures/Chat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetChatConsole.addTab(self.tabChat, icon, _fromUtf8(""))
        self.tabPlugins = QtGui.QWidget()
        self.tabPlugins.setObjectName(_fromUtf8("tabPlugins"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabPlugins)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.splitter_2 = QtGui.QSplitter(self.tabPlugins)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.textBrowserPlugin = QtGui.QTextBrowser(self.splitter_2)
        self.textBrowserPlugin.setObjectName(_fromUtf8("textBrowserPlugin"))
        self.treeWidgetPluginList = QtGui.QTreeWidget(self.splitter_2)
        self.treeWidgetPluginList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidgetPluginList.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidgetPluginList.setIndentation(5)
        self.treeWidgetPluginList.setRootIsDecorated(False)
        self.treeWidgetPluginList.setHeaderHidden(True)
        self.treeWidgetPluginList.setColumnCount(1)
        self.treeWidgetPluginList.setObjectName(_fromUtf8("treeWidgetPluginList"))
        self.treeWidgetPluginList.header().setVisible(False)
        self.treeWidgetPluginList.header().setDefaultSectionSize(20)
        self.treeWidgetPluginList.header().setMinimumSectionSize(20)
        self.horizontalLayout_3.addWidget(self.splitter_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../Pictures/plugins.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetChatConsole.addTab(self.tabPlugins, icon1, _fromUtf8(""))
        self.tabConsole = QtGui.QWidget()
        self.tabConsole.setObjectName(_fromUtf8("tabConsole"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabConsole)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.splitter_3 = QtGui.QSplitter(self.tabConsole)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.layoutWidget1 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.treeWidgetConsole = QtGui.QTreeWidget(self.layoutWidget1)
        self.treeWidgetConsole.setFocusPolicy(QtCore.Qt.NoFocus)
        self.treeWidgetConsole.setAlternatingRowColors(False)
        self.treeWidgetConsole.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.treeWidgetConsole.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidgetConsole.setIndentation(10)
        self.treeWidgetConsole.setRootIsDecorated(False)
        self.treeWidgetConsole.setItemsExpandable(False)
        self.treeWidgetConsole.setWordWrap(True)
        self.treeWidgetConsole.setObjectName(_fromUtf8("treeWidgetConsole"))
        self.treeWidgetConsole.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.treeWidgetConsole)
        self.lineEditConsole = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditConsole.setObjectName(_fromUtf8("lineEditConsole"))
        self.verticalLayout_2.addWidget(self.lineEditConsole)
        self.treeWidgetConsoleList = QtGui.QTreeWidget(self.splitter_3)
        self.treeWidgetConsoleList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidgetConsoleList.setFrameShape(QtGui.QFrame.StyledPanel)
        self.treeWidgetConsoleList.setFrameShadow(QtGui.QFrame.Sunken)
        self.treeWidgetConsoleList.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidgetConsoleList.setRootIsDecorated(False)
        self.treeWidgetConsoleList.setItemsExpandable(False)
        self.treeWidgetConsoleList.setExpandsOnDoubleClick(False)
        self.treeWidgetConsoleList.setObjectName(_fromUtf8("treeWidgetConsoleList"))
        self.treeWidgetConsoleList.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidgetConsoleList.header().setVisible(False)
        self.horizontalLayout_4.addWidget(self.splitter_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../Pictures/console.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetChatConsole.addTab(self.tabConsole, icon2, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidgetChatConsole)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.pushButtonStopStart = QtGui.QPushButton(self.centralwidget)
        self.pushButtonStopStart.setObjectName(_fromUtf8("pushButtonStopStart"))
        self.gridLayout.addWidget(self.pushButtonStopStart, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetChatConsole.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButtonStopStart, self.lineEditConsole)
        MainWindow.setTabOrder(self.lineEditConsole, self.treeWidgetConsole)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetChat.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Player Chat", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetPlayersList.setSortingEnabled(False)
        self.tabWidgetChatConsole.setTabText(self.tabWidgetChatConsole.indexOf(self.tabChat), QtGui.QApplication.translate("MainWindow", "Chat", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetPluginList.setSortingEnabled(True)
        self.treeWidgetPluginList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "checked", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetChatConsole.setTabText(self.tabWidgetChatConsole.indexOf(self.tabPlugins), QtGui.QApplication.translate("MainWindow", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetConsole.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetChatConsole.setTabText(self.tabWidgetChatConsole.indexOf(self.tabConsole), QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStopStart.setText(QtGui.QApplication.translate("MainWindow", "Stop Server", None, QtGui.QApplication.UnicodeUTF8))

