# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Wed Jul 20 23:44:09 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(838, 665)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidgetChatConsole = QtGui.QTabWidget(self.centralwidget)
        self.tabWidgetChatConsole.setEnabled(True)
        self.tabWidgetChatConsole.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidgetChatConsole.setAutoFillBackground(False)
        self.tabWidgetChatConsole.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidgetChatConsole.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidgetChatConsole.setTabsClosable(False)
        self.tabWidgetChatConsole.setObjectName(_fromUtf8("tabWidgetChatConsole"))
        self.tabChat = QtGui.QWidget()
        self.tabChat.setObjectName(_fromUtf8("tabChat"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabChat)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeWidgetChat = QtGui.QTreeWidget(self.tabChat)
        self.treeWidgetChat.setProperty(_fromUtf8("showDropIndicator"), False)
        self.treeWidgetChat.setAlternatingRowColors(True)
        self.treeWidgetChat.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.treeWidgetChat.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidgetChat.setIndentation(10)
        self.treeWidgetChat.setRootIsDecorated(False)
        self.treeWidgetChat.setItemsExpandable(False)
        self.treeWidgetChat.setAnimated(True)
        self.treeWidgetChat.setWordWrap(True)
        self.treeWidgetChat.setObjectName(_fromUtf8("treeWidgetChat"))
        self.treeWidgetChat.header().setVisible(False)
        self.verticalLayout.addWidget(self.treeWidgetChat)
        self.lineEditMessage = QtGui.QLineEdit(self.tabChat)
        self.lineEditMessage.setObjectName(_fromUtf8("lineEditMessage"))
        self.verticalLayout.addWidget(self.lineEditMessage)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.textBrowserPlayerList = QtGui.QTextBrowser(self.tabChat)
        self.textBrowserPlayerList.setEnabled(True)
        self.textBrowserPlayerList.setMaximumSize(QtCore.QSize(141, 16777215))
        self.textBrowserPlayerList.setObjectName(_fromUtf8("textBrowserPlayerList"))
        self.horizontalLayout_2.addWidget(self.textBrowserPlayerList)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../Pictures/Chat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetChatConsole.addTab(self.tabChat, icon, _fromUtf8(""))
        self.tabPlugins = QtGui.QWidget()
        self.tabPlugins.setObjectName(_fromUtf8("tabPlugins"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tabPlugins)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.textBrowserPlugin = QtGui.QTextBrowser(self.tabPlugins)
        self.textBrowserPlugin.setObjectName(_fromUtf8("textBrowserPlugin"))
        self.horizontalLayout_7.addWidget(self.textBrowserPlugin)
        self.treeWidgetPluginList = QtGui.QTreeWidget(self.tabPlugins)
        self.treeWidgetPluginList.setMaximumSize(QtCore.QSize(141, 16777215))
        self.treeWidgetPluginList.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidgetPluginList.setIndentation(5)
        self.treeWidgetPluginList.setRootIsDecorated(False)
        self.treeWidgetPluginList.setHeaderHidden(True)
        self.treeWidgetPluginList.setObjectName(_fromUtf8("treeWidgetPluginList"))
        self.treeWidgetPluginList.header().setVisible(False)
        self.treeWidgetPluginList.header().setDefaultSectionSize(20)
        self.treeWidgetPluginList.header().setMinimumSectionSize(20)
        self.horizontalLayout_7.addWidget(self.treeWidgetPluginList)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../Pictures/plugins.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetChatConsole.addTab(self.tabPlugins, icon1, _fromUtf8(""))
        self.tabConsole = QtGui.QWidget()
        self.tabConsole.setObjectName(_fromUtf8("tabConsole"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tabConsole)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.treeWidgetConsole = QtGui.QTreeWidget(self.tabConsole)
        self.treeWidgetConsole.setAlternatingRowColors(False)
        self.treeWidgetConsole.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.treeWidgetConsole.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidgetConsole.setIndentation(10)
        self.treeWidgetConsole.setRootIsDecorated(False)
        self.treeWidgetConsole.setItemsExpandable(False)
        self.treeWidgetConsole.setWordWrap(True)
        self.treeWidgetConsole.setObjectName(_fromUtf8("treeWidgetConsole"))
        self.treeWidgetConsole.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.treeWidgetConsole)
        self.lineEditConsole = QtGui.QLineEdit(self.tabConsole)
        self.lineEditConsole.setObjectName(_fromUtf8("lineEditConsole"))
        self.verticalLayout_2.addWidget(self.lineEditConsole)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.treeWidgetConsoleList = QtGui.QTreeWidget(self.tabConsole)
        self.treeWidgetConsoleList.setMaximumSize(QtCore.QSize(141, 16777215))
        self.treeWidgetConsoleList.setFrameShape(QtGui.QFrame.StyledPanel)
        self.treeWidgetConsoleList.setFrameShadow(QtGui.QFrame.Sunken)
        self.treeWidgetConsoleList.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidgetConsoleList.setRootIsDecorated(False)
        self.treeWidgetConsoleList.setItemsExpandable(False)
        self.treeWidgetConsoleList.setExpandsOnDoubleClick(False)
        self.treeWidgetConsoleList.setObjectName(_fromUtf8("treeWidgetConsoleList"))
        self.treeWidgetConsoleList.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidgetConsoleList.header().setVisible(False)
        self.verticalLayout_4.addWidget(self.treeWidgetConsoleList)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(92)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.toolButtonAddConsole = QtGui.QToolButton(self.tabConsole)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/plus-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonAddConsole.setIcon(icon2)
        self.toolButtonAddConsole.setObjectName(_fromUtf8("toolButtonAddConsole"))
        self.horizontalLayout_4.addWidget(self.toolButtonAddConsole)
        self.toolButtonRemoveConsole = QtGui.QToolButton(self.tabConsole)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/delete-17.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonRemoveConsole.setIcon(icon3)
        self.toolButtonRemoveConsole.setObjectName(_fromUtf8("toolButtonRemoveConsole"))
        self.horizontalLayout_4.addWidget(self.toolButtonRemoveConsole)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../Pictures/console.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetChatConsole.addTab(self.tabConsole, icon4, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidgetChatConsole)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.pushButtonStopStart = QtGui.QPushButton(self.centralwidget)
        self.pushButtonStopStart.setObjectName(_fromUtf8("pushButtonStopStart"))
        self.gridLayout.addWidget(self.pushButtonStopStart, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 838, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetChatConsole.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButtonStopStart, self.lineEditConsole)
        MainWindow.setTabOrder(self.lineEditConsole, self.treeWidgetConsole)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetChat.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Player Chat", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetChatConsole.setTabText(self.tabWidgetChatConsole.indexOf(self.tabChat), QtGui.QApplication.translate("MainWindow", "Chat", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetPluginList.setSortingEnabled(True)
        self.treeWidgetPluginList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "checked", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetPluginList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetChatConsole.setTabText(self.tabWidgetChatConsole.indexOf(self.tabPlugins), QtGui.QApplication.translate("MainWindow", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetConsole.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonAddConsole.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonRemoveConsole.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetChatConsole.setTabText(self.tabWidgetChatConsole.indexOf(self.tabConsole), QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStopStart.setText(QtGui.QApplication.translate("MainWindow", "Stop Server", None, QtGui.QApplication.UnicodeUTF8))

